# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 04:08
from __future__ import unicode_literals

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_messaging'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='buyer_id',
            field=models.ForeignKey(null=True, on_delete=models.SET(api.models.get_deleted_user), related_name='items_bought', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='owner_id',
            field=models.ForeignKey(default=1, on_delete=models.SET(api.models.get_deleted_user), related_name='posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='messaging',
            name='body',
            field=models.TextField(unique=True),
        ),
    ]
