# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170727_2339'),
        ('api', '0004_additional_post_attributes'),
    ]

    operations = [
    ]
