# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 19:07
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20170728_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Potential_buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_buyer', to='api.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Seller_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_rating', to='api.Post')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddField(
            model_name='seller_rating',
            name='rater_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_seller_rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seller_rating',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_as_a_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='potential_buyer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_interested_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyer_rating',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_as_a_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyer_rating',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_rating', to='api.Post'),
        ),
        migrations.AddField(
            model_name='buyer_rating',
            name='rater_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_buyer_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
