# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170728_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='title'),
        ),
    ]
